// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC26hY07w6OCrNYkKcOJnyYQxouroiSKeI',
    appId: '1:261974851386:web:bc267ec5063b06b1431a03',
    messagingSenderId: '261974851386',
    projectId: 'chess-traps-achraf',
    authDomain: 'chess-traps-achraf.firebaseapp.com',
    storageBucket: 'chess-traps-achraf.firebasestorage.app',
    measurementId: 'G-M0W2CGGE68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnEGrSHxsLV1etgdHNr9Zdu-LRkxzs4xs',
    appId: '1:261974851386:android:750bce1e5b539ef8431a03',
    messagingSenderId: '261974851386',
    projectId: 'chess-traps-achraf',
    storageBucket: 'chess-traps-achraf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2EJ5lrZ98xSx1iIq8StfG9XAtUlhU1W4',
    appId: '1:261974851386:ios:c5c94616f508ceda431a03',
    messagingSenderId: '261974851386',
    projectId: 'chess-traps-achraf',
    storageBucket: 'chess-traps-achraf.firebasestorage.app',
    iosBundleId: 'chesstraps.achrafcyber.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2EJ5lrZ98xSx1iIq8StfG9XAtUlhU1W4',
    appId: '1:261974851386:ios:c5c94616f508ceda431a03',
    messagingSenderId: '261974851386',
    projectId: 'chess-traps-achraf',
    storageBucket: 'chess-traps-achraf.firebasestorage.app',
    iosBundleId: 'chesstraps.achrafcyber.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC26hY07w6OCrNYkKcOJnyYQxouroiSKeI',
    appId: '1:261974851386:web:82dc80c405ba729e431a03',
    messagingSenderId: '261974851386',
    projectId: 'chess-traps-achraf',
    authDomain: 'chess-traps-achraf.firebaseapp.com',
    storageBucket: 'chess-traps-achraf.firebasestorage.app',
    measurementId: 'G-27ZECKCK7Y',
  );
}
