import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Use",
  description: "Terms of use for the Chess Traps app and website.",
};

export default function TermsPage() {
  return (
    <main className="legal-page">
      <h1>Terms of Use</h1>
      <p className="updated">Last updated: July 2026</p>

      <p>
        These terms apply to the Chess Traps mobile app and this website. By downloading
        or using Chess Traps, you agree to the following.
      </p>

      <h2>Using the app</h2>
      <p>
        Chess Traps is provided for personal, non-commercial use to learn and practice
        chess openings. You may not redistribute, resell, or reverse-engineer the app,
        or attempt to disrupt the Stockfish-powered analysis service it depends on.
      </p>

      <h2>Content</h2>
      <p>
        Trap sequences, opening names, and annotations are drawn from publicly documented
        chess theory. Game analysis is generated by the Stockfish chess engine and is
        provided for educational purposes only.
      </p>

      <h2>No warranty</h2>
      <p>
        The app is provided &quot;as is,&quot; without warranty of any kind. We do not
        guarantee that engine evaluations, hints, or move explanations are error-free.
      </p>

      <h2>Changes</h2>
      <p>
        We may update these terms as the app evolves. Continued use of the app after a
        change means you accept the updated terms.
      </p>

      <h2>Contact</h2>
      <p>
        Questions about these terms can be sent to{" "}
        <a href="mailto:achrafsimbre@gmail.com">achrafsimbre@gmail.com</a>. See also our{" "}
        <a href="https://achraf-cyber.github.io/privacy/privacy-policy.html">
          Privacy Policy
        </a>
        .
      </p>
    </main>
  );
}
